version: '3'

services:
  ftp:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009" # Пассивные порты
    environment:
      - FTP_USER_NAME=user
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/home/user
    volumes:
      - ./ftpdata:${FTP_PATH}
  
  bff_server:
    build: .
    ports:
      - "1000:3000"
    depends_on:
      - ftp